FROM jenkins/inbound-agent

USER root

# Install base packages
RUN apt-get update && apt-get install -y \
    ca-certificates curl gnupg lsb-release

# Add Docker packages
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker packages
RUN apt-get update && \ 
    apt-get -y install docker-ce-cli

# Add jenkins user to docker group (GID has to be the same as host's GID)
ARG DOCKER_GID
RUN groupadd -g ${DOCKER_GID} docker && gpasswd -a jenkins docker

USER jenkins
WORKDIR /home/jenkins/agent
